reviewers:
  defaults:
    - code-owners
  groups:
    code-owners:
      - Nashqueue
      - tzdybal
      - gupadhyaya
    rollkit:
      - Manav-Aggarwal
      - S1nus
      - tuxcanfly
    celestia:
      - team:celestia
files:
  '**':
    - code-owners
    - rollkit
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 3
