name: docker-build-publish

# Trigger on all push events, new semantic version tags, and all PRs
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
  merge_group:

jobs:
  docker-build:
    permissions:
      contents: write
      packages: write
    uses: rollkit/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.5.0
    with:
      dockerfile: Dockerfile
    secrets: inherit
